name: tmap
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.11.26=h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmpdec=4.0.0=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py311h06a4308_0
  - python=3.11.11=he870216_0
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py311h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - einops==0.8.0
      - filelock==3.13.1
      - fonttools==4.55.3
      - fsspec==2024.2.0
      - h5py==3.12.1
      - huggingface-hub==0.27.0
      - idna==3.10
      - image-similarity-measures==0.3.6
      - imageio==2.36.1
      - jinja2==3.1.3
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.26.3
      - opencv-python==4.10.0.84
      - packaging==24.2
      - pandas==2.2.3
      - phasepack==1.5
      - pillow==10.2.0
      - protobuf==5.29.2
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-image==0.20.0
      - scipy==1.14.1
      - sewar==0.4.6
      - six==1.17.0
      - sympy==1.13.1
      - tensorboardx==2.6.2.2
      - tifffile==2024.12.12
      - timm==1.0.12
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - triton==3.1.0
      - typing-extensions==4.9.0
      - tzdata==2024.2
      - urllib3==2.3.0
